// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('~icons/el/button')['default']
    ElCol: typeof import('~icons/el/col')['default']
    ElePosition: typeof import('~icons/el/e-position')['default']
    EleUnlock: typeof import('~icons/el/e-unlock')['default']
    EleUser: typeof import('~icons/el/e-user')['default']
    ElForm: typeof import('~icons/el/form')['default']
    ElFormItem: typeof import('~icons/el/form-item')['default']
    ElIcon: typeof import('~icons/el/icon')['default']
    ElInput: typeof import('~icons/el/input')['default']
    ElTabPane: typeof import('~icons/el/tab-pane')['default']
    ElTabs: typeof import('~icons/el/tabs')['default']
  }
}

export { }
